.pragma library

// Taskbar icon set: Omarchy-style line icons on a 24px grid. "%C" is the
// draw colour, filled in at runtime so one drawing serves dark and light
// themes and every state (active, inactive, minimized).
//
// GENERATED by the taskbar-icons skill's icon-build from the icon scripts in
// the omarchy-desktop repo (icon-src/icons/<name>.icon.py; the spec is
// icon-src/ICON-SPEC.md). Don't edit the entries here: change the script and
// run icon-build.
var icons = {
  "aether": "<path d=\"M5.5 20L12 4l6.5 16\"/><path d=\"M3.5 14.8c2.7-1.9 5.2-.2 8.5-.9s5.3-2.6 8.5-.9\"/>",
  "app": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"2.5\"/><path d=\"M3.5 8.5h17\"/><circle cx=\"6\" cy=\"6.5\" r=\"0.6\" fill=\"%C\" stroke=\"none\"/><circle cx=\"8\" cy=\"6.5\" r=\"0.6\" fill=\"%C\" stroke=\"none\"/>",
  "base": "<path d=\"M7 3.5h7.5l5 5V19a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 19V5A1.5 1.5 0 0 1 7 3.5z\"/><ellipse cx=\"12.5\" cy=\"10\" rx=\"4\" ry=\"1.5\"/><path d=\"M8.5 10v7c0 .85 1.8 1.5 4 1.5s4-.65 4-1.5v-7M8.5 13.5c0 .85 1.8 1.5 4 1.5s4-.65 4-1.5\"/>",
  "basecamp": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><path d=\"M4.1 14.8c2.3-2.9 4.2-4.9 5.8-4.9 1.8 0 2.3 3.2 4.1 3.2 1.3 0 2.6-1.2 5.8-4.4\"/>",
  "bluetui": "<path d=\"M7 7.5l10 9L12 21V3l5 4.5-10 9\"/>",
  "browser": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><ellipse cx=\"12\" cy=\"12\" rx=\"3.8\" ry=\"8.5\"/><path d=\"M3.5 12h17\"/>",
  "btop": "<rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"3\"/><path d=\"M7.5 16v-3M10.5 16V8.5M13.5 16v-5M16.5 16V10\"/>",
  "calc": "<path d=\"M7 3.5h7.5l5 5V19a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 19V5A1.5 1.5 0 0 1 7 3.5z\"/><path d=\"M5.5 11.5h14M5.5 16h14M11 11.5v9\"/>",
  "calendar": "<rect x=\"3.5\" y=\"5\" width=\"17\" height=\"15\" rx=\"2.5\"/><path d=\"M3.5 9.5h17M8 3v4M16 3v4\"/><circle cx=\"8.3\" cy=\"14\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"12\" cy=\"14\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"15.7\" cy=\"14\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/>",
  "chat": "<path d=\"M4.5 6.5a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-7l-4 3.5v-3.5a2 2 0 0 1-2-2z\"/>",
  "chatgpt": "<path d=\"M15.4 6.7L15.4 17.3A3.4 3.4 0 0 1 8.6 17.3L8.6 6.7A3.4 3.4 0 0 1 15.4 6.7Z\"/><path d=\"M18.29 12.29L9.11 17.59A3.4 3.4 0 0 1 5.71 11.71L14.89 6.41A3.4 3.4 0 0 1 18.29 12.29Z\"/><path d=\"M14.89 17.59L5.71 12.29A3.4 3.4 0 0 1 9.11 6.41L18.29 11.71A3.4 3.4 0 0 1 14.89 17.59Z\"/>",
  "chrome": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><circle cx=\"12\" cy=\"12\" r=\"3.2\"/><path d=\"M12 8.8L19.87 8.8M14.77 13.6L10.83 20.42M9.23 13.6L5.29 6.78\"/>",
  "claude": "<path d=\"M12 12L12 3M12 12L16.22 6.54M12 12L19.27 8.21M12 12L19.23 13.56M12 12L18.85 17.53M12 12L13.19 18.49M12 12L10.18 20.3M12 12L6.4 16.36M12 12L3.21 13.42M12 12L6.08 8.65M12 12L7.39 5.59\"/>",
  "cliamp": "<rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"3\"/><path d=\"M7 11v2M9.5 9v6M12 7.5v9M14.5 9.5v5M17 11v2\"/>",
  "code": "<path d=\"M8.5 7.5L4 12l4.5 4.5M15.5 7.5L20 12l-4.5 4.5M13.2 5.5l-2.4 13\"/>",
  "codex": "<path d=\"M14.79 5.26A3.05 3.05 0 0 1 18.74 9.21A3.05 3.05 0 0 1 18.74 14.79A3.05 3.05 0 0 1 14.79 18.74A3.05 3.05 0 0 1 9.21 18.74A3.05 3.05 0 0 1 5.26 14.79A3.05 3.05 0 0 1 5.26 9.21A3.05 3.05 0 0 1 9.21 5.26A3.05 3.05 0 0 1 14.79 5.26Z\"/><path d=\"M9.3 10l2 2-2 2M12.9 14.3h2.2\"/>",
  "contacts": "<circle cx=\"12\" cy=\"8.8\" r=\"3.3\"/><path d=\"M5.5 19.5c.9-3 3.4-5 6.5-5s5.6 2 6.5 5\"/>",
  "copilot": "<path d=\"M4.5 12.5C4.5 7.8 7.6 5 12 5C16.4 5 19.5 7.8 19.5 12.5V15.2C19.5 17.8 16.4 19.5 12 19.5C7.6 19.5 4.5 17.8 4.5 15.2Z\"/><rect x=\"6.2\" y=\"8\" width=\"5.2\" height=\"4.4\" rx=\"2\"/><rect x=\"12.6\" y=\"8\" width=\"5.2\" height=\"4.4\" rx=\"2\"/><circle cx=\"10\" cy=\"15.6\" r=\"0.9\" fill=\"%C\" stroke=\"none\"/><circle cx=\"14\" cy=\"15.6\" r=\"0.9\" fill=\"%C\" stroke=\"none\"/>",
  "crush": "<path d=\"M12 19.2C7.2 16 4.2 13.2 4.2 9.8C4.2 7.4 6 5.6 8.3 5.6C9.8 5.6 11.2 6.4 12 7.7C12.8 6.4 14.2 5.6 15.7 5.6C18 5.6 19.8 7.4 19.8 9.8C19.8 13.2 16.8 16 12 19.2Z\"/>",
  "cursor": "<path d=\"M12 3.2L19.6 7.6V16.4L12 20.8L4.4 16.4V7.6Z\"/><path d=\"M4.4 7.6L12 12L19.6 7.6M12 12V20.8\"/>",
  "discord": "<path d=\"M8.77 5.65c-1.57 0.29 -2.94 0.88 -4.21 1.67 -1.37 2.94 -1.76 5.88 -1.37 8.82 1.37 1.08 2.94 1.76 4.51 2.16l1.08 -1.76M15.23 5.65c1.57 0.29 2.94 0.88 4.21 1.67 1.37 2.94 1.76 5.88 1.37 8.82 -1.37 1.08 -2.94 1.76 -4.51 2.16l-1.08 -1.76M7.69 15.15c2.84 1.27 5.78 1.27 8.62 0M8.67 7.12c2.25 -0.59 4.41 -0.59 6.66 0\"/><circle cx=\"9.45\" cy=\"11.53\" r=\"1.15\" fill=\"%C\" stroke=\"none\"/><circle cx=\"14.55\" cy=\"11.53\" r=\"1.15\" fill=\"%C\" stroke=\"none\"/>",
  "disks": "<rect x=\"3\" y=\"6\" width=\"18\" height=\"12\" rx=\"2.5\"/><path d=\"M3 13.5h18\"/><circle cx=\"17.2\" cy=\"15.8\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/>",
  "docker": "<rect x=\"5.4\" y=\"9\" width=\"3.4\" height=\"3.2\" rx=\"0.6\"/><rect x=\"9.8\" y=\"9\" width=\"3.4\" height=\"3.2\" rx=\"0.6\"/><rect x=\"14.2\" y=\"9\" width=\"3.4\" height=\"3.2\" rx=\"0.6\"/><rect x=\"9.8\" y=\"4.8\" width=\"3.4\" height=\"3.2\" rx=\"0.6\"/><path d=\"M3 14.5h18c-1 3.5-4.2 5.5-9 5.5s-8-2-9-5.5z\"/>",
  "document": "<path d=\"M6.5 3.5h7l4 4v13h-11z\"/><path d=\"M13.5 3.5v4h4M9 12h6M9 15.5h6\"/>",
  "draw": "<path d=\"M7 3.5h7.5l5 5V19a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 19V5A1.5 1.5 0 0 1 7 3.5z\"/><circle cx=\"9.8\" cy=\"11.6\" r=\"2.3\"/><path d=\"M14.4 13.2l2.8 4.8h-5.6z\"/>",
  "dua": "<path d=\"M12 3.5v8.5h8.5A8.5 8.5 0 0 0 12 3.5z\"/><path d=\"M20.1 14.6A8.5 8.5 0 1 1 9.4 3.9\"/>",
  "edge": "<path d=\"M20.9 11.4a9 9 0 1 0 -1.6 5.8\"/><path d=\"M20.9 11.4c.2 3 -5 2.4 -6.9 1.5c1.4 -1.6 .4 -4 -2.3 -3.9c-1.7 .1 -2.9 1.2 -2.8 3.2c.3 4 4.4 6.2 10.4 4.8\"/><path d=\"M3 12.6c-.3 -4 8.7 -7.2 11.3 -2.7\"/>",
  "fastfetch": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><path d=\"M12 11v5.5\"/><circle cx=\"12\" cy=\"7.9\" r=\"1.05\" fill=\"%C\" stroke=\"none\"/>",
  "folder": "<path d=\"M3.5 7.5a2 2 0 0 1 2-2h3.8l2 2.2h7.2a2 2 0 0 1 2 2v7.8a2 2 0 0 1-2 2h-13a2 2 0 0 1-2-2z\"/>",
  "gemini": "<path d=\"M12 3.2C12.4 8.2 15.8 11.6 20.8 12C15.8 12.4 12.4 15.8 12 20.8C11.6 15.8 8.2 12.4 3.2 12C8.2 11.6 11.6 8.2 12 3.2Z\"/>",
  "ghostty": "<path d=\"M5.5 20.5V11a6.5 6.5 0 0 1 13 0v9.5l-2.17-1.5-2.16 1.5-2.17-1.5-2.17 1.5-2.16-1.5z\"/><path d=\"M8.9 10l1.9 1.4-1.9 1.4M12.9 12.8h2.3\"/>",
  "git": "<circle cx=\"6.5\" cy=\"6\" r=\"2.2\"/><circle cx=\"6.5\" cy=\"18\" r=\"2.2\"/><circle cx=\"17.5\" cy=\"7.5\" r=\"2.2\"/><path d=\"M6.5 8.2v7.6M17.5 9.7c0 4.3-5 4-9.3 6.9\"/>",
  "github": "<path d=\"M9 19c-4.3 1.4-4.3-2.5-6-3m12 5v-3.5c0-1 .1-1.4-.5-2 2.8-.3 5.5-1.4 5.5-6a4.6 4.6 0 0 0-1.3-3.2 4.2 4.2 0 0 0-.1-3.2s-1.1-.3-3.5 1.3a12.3 12.3 0 0 0-6.2 0C6.5 2.8 5.4 3.1 5.4 3.1a4.2 4.2 0 0 0-.1 3.2A4.6 4.6 0 0 0 4 9.5c0 4.6 2.7 5.7 5.5 6-.6.6-.6 1.2-.5 2V21\"/>",
  "grok": "<path d=\"M17.3 6.1A7.6 7.6 0 1 0 19 15.6\"/><path d=\"M5 20.4L20.4 4.9\"/>",
  "hermes": "<path d=\"M4 16C6.6 11.4 11.4 7.8 20.2 5.8C17 8.4 15.4 9.8 14.2 11\"/><path d=\"M4 16C7.4 14.2 11.6 12.8 18 12.2C15.6 13.8 13.6 15 12.2 15.6\"/><path d=\"M4 16C6.8 16.8 10 17.4 14.6 17.2C12.2 18.6 9.4 19.2 7 19\"/>",
  "htop": "<path d=\"M5 5.5H3.5v13H5M19 5.5h1.5v13H19\"/><path d=\"M7 8.5h10M7 12h5M7 15.5h7.5\"/>",
  "image": "<rect x=\"3.5\" y=\"4.5\" width=\"17\" height=\"15\" rx=\"2.5\"/><circle cx=\"9\" cy=\"9.5\" r=\"1.6\"/><path d=\"M20.5 15.5L16 11l-8 8.5\"/>",
  "impala": "<path d=\"M3.5 9.5a12 12 0 0 1 17 0M6.5 12.8a7.7 7.7 0 0 1 11 0M9.4 16a3.6 3.6 0 0 1 5.2 0\"/><circle cx=\"12\" cy=\"19\" r=\"1.2\" fill=\"%C\" stroke=\"none\"/>",
  "impress": "<path d=\"M7 3.5h7.5l5 5V19a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 19V5A1.5 1.5 0 0 1 7 3.5z\"/><path d=\"M9 17.5v-2.5M12.5 17.5v-5.5M16 17.5v-8\"/>",
  "imv": "<path d=\"M3.5 8V5.5a2 2 0 0 1 2-2H8M16 3.5h2.5a2 2 0 0 1 2 2V8M20.5 16v2.5a2 2 0 0 1-2 2H16M8 20.5H5.5a2 2 0 0 1-2-2V16\"/><path d=\"M7 16.5l3.5-4 2.5 2.5 1.5-1.5 2.5 3\"/><circle cx=\"15\" cy=\"8.8\" r=\"1.4\"/>",
  "kdenlive": "<path d=\"M10.5 6.5v13\"/><path d=\"M8.6 4h3.8l-1.9 2.6z\" fill=\"%C\"/><path d=\"M4.5 9.5h3M3.5 13h4M4.5 16.5h3\"/><path d=\"M13.8 8.2l6.2 4-6.2 4z\"/>",
  "keyboard": "<rect x=\"3\" y=\"6\" width=\"18\" height=\"12\" rx=\"2.5\"/><path d=\"M8.5 14.8h7\"/><circle cx=\"7\" cy=\"9.6\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"10.3\" cy=\"9.6\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"13.7\" cy=\"9.6\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"17\" cy=\"9.6\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/>",
  "lazydocker": "<rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"3\"/><rect x=\"7.2\" y=\"11.6\" width=\"4.2\" height=\"4.2\" rx=\"0.6\"/><rect x=\"12.6\" y=\"11.6\" width=\"4.2\" height=\"4.2\" rx=\"0.6\"/><rect x=\"9.9\" y=\"6.9\" width=\"4.2\" height=\"3.6\" rx=\"0.6\"/>",
  "lazygit": "<rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"3\"/><circle cx=\"8.5\" cy=\"8.6\" r=\"1.6\" fill=\"%C\" stroke=\"none\"/><circle cx=\"8.5\" cy=\"15.4\" r=\"1.6\" fill=\"%C\" stroke=\"none\"/><circle cx=\"15.5\" cy=\"8.6\" r=\"1.6\" fill=\"%C\" stroke=\"none\"/><path d=\"M8.5 8.6v6.8M15.5 8.6c0 3.4-3 3.4-7 5.4\"/>",
  "libreoffice": "<path d=\"M7 3.5h7.5l5 5V19a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 19V5A1.5 1.5 0 0 1 7 3.5z\"/>",
  "localsend": "<path d=\"M10.27 3.88A8.3 8.3 0 0 1 13.73 3.88M16.52 5.04A8.3 8.3 0 0 1 18.96 7.48M20.12 10.27A8.3 8.3 0 0 1 20.12 13.73M18.96 16.52A8.3 8.3 0 0 1 16.52 18.96M13.73 20.12A8.3 8.3 0 0 1 10.27 20.12M7.48 18.96A8.3 8.3 0 0 1 5.04 16.52M3.88 13.73A8.3 8.3 0 0 1 3.88 10.27M5.04 7.48A8.3 8.3 0 0 1 7.48 5.04\"/><circle cx=\"12\" cy=\"12\" r=\"3.6\" fill=\"%C\" stroke=\"none\"/>",
  "mail": "<rect x=\"3.2\" y=\"5.5\" width=\"17.6\" height=\"13\" rx=\"2.5\"/><path d=\"M4 7.3l8 5.9 8-5.9\"/>",
  "maps": "<path d=\"M12 21s-6.5-6-6.5-11a6.5 6.5 0 0 1 13 0c0 5-6.5 11-6.5 11z\"/><circle cx=\"12\" cy=\"10\" r=\"2.3\"/>",
  "math": "<path d=\"M7 3.5h7.5l5 5V19a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 19V5A1.5 1.5 0 0 1 7 3.5z\"/><path d=\"M7.8 14.2h1.5l1.9 3.8 2.8-8h3.3\"/>",
  "messages": "<path d=\"M4.5 6.5a2 2 0 0 1 2-2h11a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-7l-4 3.5v-3.5a2 2 0 0 1-2-2z\"/><path d=\"M8.3 9h7.4M8.3 12h4.6\"/>",
  "monitor": "<rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"3\"/><path d=\"M6.5 13h2.3l1.7-4.2 3 7.4 1.7-4.2h2.3\"/>",
  "moonlight": "<circle cx=\"12\" cy=\"12\" r=\"8.8\"/><path d=\"M12 5.5v13M5.5 12h13M7.4 7.4l9.2 9.2M16.6 7.4l-9.2 9.2\"/>",
  "mpv": "<circle cx=\"12\" cy=\"12\" r=\"8.8\"/><circle cx=\"12.9\" cy=\"12.9\" r=\"5.2\"/><path d=\"M11.6 10.6l3.7 2.3-3.7 2.3z\"/>",
  "muse": "<path d=\"M12 12C10.1 8.7 8.6 7.2 6.7 7.2C4.6 7.2 3.2 9.4 3.2 12C3.2 14.6 4.6 16.8 6.7 16.8C8.6 16.8 10.1 15.3 12 12C13.9 8.7 15.4 7.2 17.3 7.2C19.4 7.2 20.8 9.4 20.8 12C20.8 14.6 19.4 16.8 17.3 16.8C15.4 16.8 13.9 15.3 12 12Z\"/>",
  "music": "<path d=\"M9 17.5V6.5l10-2v11\"/><circle cx=\"6.8\" cy=\"17.5\" r=\"2.2\"/><circle cx=\"16.8\" cy=\"15.5\" r=\"2.2\"/>",
  "neovim": "<path d=\"M6.25 18.9V5.1l11.5 13.8V5.1\"/>",
  "network": "<circle cx=\"12\" cy=\"12\" r=\"2.3\"/><circle cx=\"12\" cy=\"4.8\" r=\"1.8\"/><circle cx=\"5.5\" cy=\"17.2\" r=\"1.8\"/><circle cx=\"18.5\" cy=\"17.2\" r=\"1.8\"/><path d=\"M12 6.6v3.1M7.1 16.1l2.9-2.2M16.9 16.1l-2.9-2.2\"/>",
  "node": "<path d=\"M12 3l7.8 4.5v9L12 21l-7.8-4.5v-9z\"/><path d=\"M9.6 15.5v-3.6a2.4 2.4 0 0 1 4.8 0v3.6\"/>",
  "obs": "<circle cx=\"12\" cy=\"12\" r=\"8.8\"/><circle cx=\"12\" cy=\"7.8\" r=\"2.3\"/><circle cx=\"15.64\" cy=\"14.1\" r=\"2.3\"/><circle cx=\"8.36\" cy=\"14.1\" r=\"2.3\"/>",
  "obsidian": "<path d=\"M14 3.2l4.6 5.9-1 8.2-5.4 3.6-6.2-4.6 2.4-8.3z\"/><path d=\"M8.4 8l2.5 4.5 7.7-3.4M10.9 12.5l1.3 8.3\"/>",
  "omacalc": "<rect x=\"5.5\" y=\"3\" width=\"13\" height=\"18\" rx=\"2.5\"/><path d=\"M8.5 7h7\"/><circle cx=\"9\" cy=\"11.5\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"12\" cy=\"11.5\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"15\" cy=\"11.5\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"9\" cy=\"14.5\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"12\" cy=\"14.5\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"15\" cy=\"14.5\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"9\" cy=\"17.5\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><path d=\"M12 17.5h3\"/>",
  "omacut": "<path d=\"M8 8H4.5A1.5 1.5 0 0 0 3 9.5v5A1.5 1.5 0 0 0 4.5 16H8M16 8h3.5A1.5 1.5 0 0 1 21 9.5v5a1.5 1.5 0 0 1-1.5 1.5H16\"/><path d=\"M10.5 4.5H8v15h2.5M13.5 4.5H16v15h-2.5\"/>",
  "omawrite": "<rect x=\"3.5\" y=\"3.5\" width=\"17\" height=\"17\" rx=\"3.5\"/><path d=\"M8 9h8M8 12h6M8 15h8\"/>",
  "omp": "<circle cx=\"12\" cy=\"12\" r=\"8.6\"/><path d=\"M8 9.4H16.2M10.3 9.4C10.3 12 10 14 9.2 15.6M13.8 9.4V14.2C13.8 15.4 14.4 15.8 15.6 15.4\"/>",
  "openclaw": "<path d=\"M5.4 20.2C4.6 15.6 5.2 11.4 7.8 8.2C10.2 5.4 13.8 4 17.8 4.4C16 6 14.8 7.6 14.2 9.6C16 9.2 17.8 9.6 19 10.6C16.8 13 13.6 14 10.6 13.4C9.2 15.4 8.6 17.6 8.8 20.2\"/>",
  "opencode": "<rect x=\"5\" y=\"4\" width=\"14\" height=\"16\" rx=\"1.2\"/><rect x=\"9\" y=\"8\" width=\"6\" height=\"8\" rx=\"0.6\"/>",
  "pdf": "<path d=\"M6 13.8V4.5a1 1 0 0 1 1-1h7l4 4v6.3\"/><path d=\"M9 8h4M9 10.8h6\"/><circle cx=\"8.6\" cy=\"17.3\" r=\"2.7\"/><circle cx=\"15.4\" cy=\"17.3\" r=\"2.7\"/><path d=\"M11.3 16.6h1.4\"/>",
  "pen": "<path d=\"M15.5 4.5l4 4L9 19H5v-4z\"/><path d=\"M13.5 6.5l4 4\"/>",
  "photos": "<path d=\"M12 12L12 4.2A3.9 3.9 0 0 0 12 12ZM12 12L19.8 12A3.9 3.9 0 0 0 12 12ZM12 12L12 19.8A3.9 3.9 0 0 0 12 12ZM12 12L4.2 12A3.9 3.9 0 0 0 12 12Z\"/>",
  "pi": "<path d=\"M4.6 9C4.9 7.9 5.8 7.4 7.2 7.4H19.4M9.4 7.4C9.4 12 8.8 15.4 7.4 18.4M15 7.4V15.6C15 17.4 16 18 17.8 17.4\"/>",
  "pinta": "<path d=\"M20.5 3.5L13.85 10.15\"/><path d=\"M13.28 12.98L11.02 10.72 12.72 9.02 14.98 11.28z\"/><path d=\"M11.02 10.72C8 10.5 6.8 12.5 6.5 14.5 6.2 16.5 5.5 18.5 3.8 20.2 7.5 20 12 18.5 13.28 12.98\"/>",
  "play": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><path d=\"M10.2 8.8l5 3.2-5 3.2z\"/>",
  "printer": "<path d=\"M7 8V3.5h10V8\"/><path d=\"M7 17H5a2 2 0 0 1-2-2v-5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v5a2 2 0 0 1-2 2h-2\"/><rect x=\"7\" y=\"13.5\" width=\"10\" height=\"7\" rx=\"1\"/><circle cx=\"17.3\" cy=\"10.8\" r=\"0.9\" fill=\"%C\" stroke=\"none\"/>",
  "python": "<path d=\"M12 8.5H8V6.5C8 4.5 9.5 3 12 3s4 1.5 4 3.5v4c0 1.1-.9 2-2 2h-4c-1.1 0-2 .9-2 2v3c0 2 1.5 3.5 4 3.5s4-1.5 4-3.5v-2h-4\"/><path d=\"M8 8.5H6.5C4.6 8.5 3.5 10 3.5 12s1.1 3.5 3 3.5H8M16 8.5h1.5c1.9 0 3 1.5 3 3.5s-1.1 3.5-3 3.5H16\"/><circle cx=\"10.4\" cy=\"5.7\" r=\"0.8\" fill=\"%C\" stroke=\"none\"/><circle cx=\"13.6\" cy=\"18.3\" r=\"0.8\" fill=\"%C\" stroke=\"none\"/>",
  "restore": "<path d=\"M4 12a8 8 0 1 0 2.4-5.7L4 8.7\"/><path d=\"M4 4.5v4.2h4.2\"/><path d=\"M12 8v4l2.8 1.8\"/>",
  "rustdesk": "<path d=\"M4.82 16.4A7.6 7.6 0 0 1 15.2 6.02\"/><path d=\"M19.18 7.6A7.6 7.6 0 0 1 8.8 17.98\"/>",
  "send": "<path d=\"M20.5 3.5l-17 7 7 2.8 2.8 7z\"/><path d=\"M20.5 3.5l-10 9.8\"/>",
  "server": "<rect x=\"4\" y=\"4.5\" width=\"16\" height=\"6.5\" rx=\"2\"/><rect x=\"4\" y=\"13\" width=\"16\" height=\"6.5\" rx=\"2\"/><path d=\"M11 7.75h5.5M11 16.25h5.5\"/><circle cx=\"7.5\" cy=\"7.75\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/><circle cx=\"7.5\" cy=\"16.25\" r=\"0.95\" fill=\"%C\" stroke=\"none\"/>",
  "steam": "<circle cx=\"12\" cy=\"12\" r=\"8.5\"/><circle cx=\"15.2\" cy=\"9.3\" r=\"2.7\"/><circle cx=\"8.4\" cy=\"15.1\" r=\"1.7\"/><path d=\"M13.2 11.1l-3.5 2.9M3.8 13.4l3.1 1.2\"/>",
  "teams": "<rect x=\"3\" y=\"6.5\" width=\"12\" height=\"11.5\" rx=\"2.5\"/><path d=\"M6.4 9.9h5.2M9 9.9v5.3\"/><circle cx=\"18.2\" cy=\"7.2\" r=\"1.9\"/><path d=\"M15 10.8h4.6c.8 0 1.4.6 1.4 1.4v2.6a3.4 3.4 0 0 1-5.4 2.8\"/>",
  "telegram": "<circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M6.1 11.9l11.2-4.6-1.8 9.6-5.3-3.6z\"/><path d=\"M10.2 13.3l4-3.4\"/>",
  "tensaku": "<path d=\"M10.3 4.9C13.7 3.75 17.6 5.8 18.9 9.6C20.1 13.1 18.4 17.25 14.8 18.6C11.1 19.9 6.6 18 5.25 14.25C4.1 10.9 5.6 6.75 9.4 5.25C11.6 4.5 14.1 4.7 15.9 5.6C16.9 6 18 5.4 19.1 4.3\"/>",
  "terminal": "<rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"3\"/><path d=\"M7.5 9.5l2.5 2.5-2.5 2.5M12.5 15h4\"/>",
  "tmux": "<rect x=\"3\" y=\"4.5\" width=\"18\" height=\"15\" rx=\"3\"/><path d=\"M12 4.5v15M12 12h9\"/>",
  "uuctl": "<path d=\"M7 4.5H4v15h3M17 4.5h3v15h-3\"/><circle cx=\"8.8\" cy=\"12\" r=\"1.7\" fill=\"%C\" stroke=\"none\"/><path d=\"M13 8.8l3.4 3.2-3.4 3.2z\" fill=\"%C\"/>",
  "video": "<rect x=\"3\" y=\"7\" width=\"12.5\" height=\"10\" rx=\"2.2\"/><path d=\"M15.5 10.5l5-2.8v8.6l-5-2.8\"/>",
  "vscode": "<path d=\"M16 3v18l4-2.5v-13z\"/><path d=\"M9.17 13.9L5 17.5l-2-1 4.33-4.5m1.74-1.8L16 3v5l-4.8 4.14\"/><path d=\"M16 16.5l-11-10-2 1L16 21\"/>",
  "whatsapp": "<path d=\"M4.3 19.7l1.25-3.9a8.1 8.1 0 1 1 2.9 2.7z\"/><path d=\"M9.4 8.9c.35 2.8 2.9 5.35 5.7 5.7l1-1.45-1.95-1-1 .75a4.6 4.6 0 0 1-2-2l.75-1-1-1.95z\"/>",
  "wiremix": "<path d=\"M6 3.5v4.2M6 11.7v8.8M12 3.5v10.2M12 17.7v2.8M18 3.5v2.2M18 9.7v10.8\"/><circle cx=\"6\" cy=\"9.7\" r=\"2\"/><circle cx=\"12\" cy=\"15.7\" r=\"2\"/><circle cx=\"18\" cy=\"7.7\" r=\"2\"/>",
  "writer": "<path d=\"M7 3.5h7.5l5 5V19a1.5 1.5 0 0 1-1.5 1.5H7A1.5 1.5 0 0 1 5.5 19V5A1.5 1.5 0 0 1 7 3.5z\"/><path d=\"M8.5 10.5h7M8.5 13.8h7M8.5 17.1h4.5\"/>",
  "x": "<path d=\"M4.3 4h4.4l11 16h-4.4z\"/><path d=\"M19.5 4l-6.4 7.1M10.9 12.9L4.5 20\"/>",
  "xournal": "<path d=\"M14 20H5.5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2H14\"/><path d=\"M6.5 9.5c1.4-.6 2.2.2 2.6 2.2s1.2 3 2.6 2.3M11.6 9.3c-2 1.2-3.3 2.9-4.9 4.7\"/><path d=\"M20.8 5.2l-5.2 8.6-1.9 1.2.1-2.2 5.2-8.6a1 1 0 0 1 1.8 1z\"/>",
  "youtube": "<rect x=\"3\" y=\"5.5\" width=\"18\" height=\"13\" rx=\"4\"/><path d=\"M10.2 9.4l4.6 2.6-4.6 2.6z\"/>",
  "youtubemusic": "<circle cx=\"12\" cy=\"12\" r=\"9\" stroke-width=\"1.4\"/><circle cx=\"12\" cy=\"12\" r=\"6\" stroke-width=\"1.4\"/><path d=\"M10.2 9.1l5 2.9-5 2.9z\" fill=\"%C\" stroke=\"none\"/>",
  "zoom": "<rect x=\"3\" y=\"3\" width=\"18\" height=\"18\" rx=\"5\"/><rect x=\"6.5\" y=\"9\" width=\"7.5\" height=\"6\" rx=\"1.5\"/><path d=\"M14 11.3l3.5-2v5.4l-3.5-2\"/>"
}

// Your own icons (~/.config/omarchy/taskbar-icons.json "icons", loaded by
// taskbar.qml): added to the set, replacing a built-in one of the same name.
function addIcons(map) {
  for (var name in map) {
    if (typeof map[name] === "string" && map[name].indexOf("<") !== -1) icons[name] = map[name]
  }
}

function svg(name, color) {
  var body = (icons[name] || icons.app).split("%C").join(color)
  return "data:image/svg+xml;utf8," + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="' + color +
    '" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round">' + body + '</svg>')
}

// The same icon with a thicker stroke, for a knockout "halo" drawn in the bar's
// background colour behind the real icon (keeps it crisp over the audio
// equalizer).
function halo(name, color, strokeWidth) {
  var body = (icons[name] || icons.app).split("%C").join(color)
  return "data:image/svg+xml;utf8," + encodeURIComponent(
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="' + color +
    '" stroke-width="' + strokeWidth + '" stroke-linecap="round" stroke-linejoin="round">' + body + '</svg>')
}
